name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  cloud_firestore:
  firebase_auth:
  provider:
  shared_preferences:
  flutter_platform_widgets:
  flutter_sheet_localization: ^1.0.0
  devicelocale:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
